Kreusada/Kreusada-Cogs

- collectables/collectables.py
Noticed that it didn't format the collectable name when you create one.
Just a small fix
> Forgot to format

- CODEOWNERS
- spoilerchannel/spoilerchannel.py
If the message is in a spoiler channel and has attachments that aren't marked with spoiler it will delete and then break out of the for loop
If there is a message with multiple attachments deleting a message once should be enough
Also, if the message has no guild then it will return out of the funcion
> [SpoilerChannel] Break out of the loop

- termino/termino.py
Sends a message on successful restart. The message sent is customizable by the user. If you would like to change the default message to something else let me know (I'm not creative ._.)
Also simplifies a few things which can be reverted if you don't want them to be changed :D
Closes #78.
> [Termino] Send message on restart

- advanceduptime/README.rst
- docs/cog_advanceduptime.rst
Repo name is case sensitive, install and info commands won't work if the repo name is capitalized.
> [Docs] Fix repo installation casing for AdvancedUptime

- minifier/minifier.py
This fixes an `AttributeError` that would raise after attempting to use `file.filename` after `file` had been converted to a string (or ioBytes, I don't know the difference :/)
> [Minifier] V0.1.2 Fix AttributeError

- vinfo/vinfo.py
Fix when `[p]vinfo mod` raises an OSError due to corrupt shared object files.
Closes #104
> [Vinfo] Fix when modules have corrupt shared object files

- dehoister/dehoister.py
came up in support and I can reproduce
> [Dehoister] Avoid using `get_context` inside `on_member_join` listener

- docs/cog_raffle.rst
- raffle/README.rst
- raffle/enums.py
- raffle/formatting.py
- raffle/helpers.py
- raffle/parser.py
- raffle/raffle.py
The `end_message` can now be pulled randomly as long as it is provided to the parser as a list. An interactive function has been created to get these results in a user friendly format.
> [Raffle] v1.1.0 `end_message` can now be randomized, various hotfixes

- termino/info.json
- termino/termino.py
Allows the owner to reset the restarted, restart, and shutdown messages.
Also allows the owner to set an announcement channel for when the bot goes offline/comes back online.
Also removes `from random import expovariate` :kappa:
Closes #120
> [Termino] V1.0.4 Rewrite and announcement channel

- raffle/commands/editor.py
- raffle/commands/informational.py
- raffle/commands/management/events.py
- raffle/converters.py
- raffle/info.json
Added two new converters: RaffleFactoryConverter and RaffleExists.
RaffleFactoryConverter checks if the user has perms to edit a given raffle, and if the raffle exists.
RaffleExists just checks if the raffle exists (informational commands).
See diffs for more details.
> [Raffle] v1.6.1 Use Converters to negate repetitive code

- docs/cog_raffle.rst
- raffle/README.rst
- raffle/commands/builder.py
- raffle/commands/editor.py
- raffle/commands/management/events.py
- raffle/info.json
- raffle/utils/enums.py
- raffle/utils/parser.py
Added the "suspense_timer" condition, where raffle owners can customize the amount of time that the bot types for when drawing a winner for the raffle. This number must be between 0 and 10, and defaults to 2 if not provided. This is the 13th raffle condition.
> [Raffle] v1.6.9 Add "suspense_timer" condition (condition #13)

- raffle/commands/builder.py
- raffle/commands/editor.py
- raffle/commands/informational.py
- raffle/commands/management/events.py
- raffle/commands/management/misc.py
- raffle/info.json
- raffle/raffle.py
- raffle/utils/cleanup.py
Increment the number of times that the cleaner is called in order to cleanup raffles for "dead" user and role IDs. Add separate functions for cleaning singular raffles, and then all raffles in a guild, and all raffles globally. Adding two new commands which will help to rejuvenate guild and global raffles.
TODO: Update documentation with new refresh commands.
> [Raffle] v1.6.12 Improve raffle cleanup efficiency

- termino/termino.py
`force_registration` is set to `True` and therefore you can't access values that aren't registered through attribute lookup. This PR uses `clear_raw()` method instead which due to its raw-ness does not check whether the value is registered. I also removed the `.all()` check since `clear_raw()` won't raise when the key isn't there anyway.
> [Termino] Fix config migration

- raffle/commands/builder.py
- raffle/utils/converters.py
Simple raffles were able to evade the raffle naming convention rules because they were not checked. This PR adds a converter to make sure the names are suitable before the raffle is created.
> [Raffle] v1.7.1 Add RaffleNameConverter for simple raffles

- pypi/pypi.py
This fixes an issue when the classifier data is over the char limit of an embed field.
Also, it didn't take me the weekend to figure out :D
Closes #177
> [Pypi] Pagify classifiers if it's over a certain length

- raffle/info.json
- raffle/utils/checks.py
- termino/termino.py
- termino/utils.py
Calls `now` every time it's supposed to be called and adds `now` as an alias for datetime.datetime.now for other cogs
> [Meta] Update datetime.now logic

- pingoverride/enums.py
Seems that `enums.py` was deleted in a repo cleanup from about a month and a half ago, which broke `pingoverride`, at least on my d.py2 bot. Not sure why it continued to work fine on my main bot, but hey.
This will restore the `enums.py` for `pingoverride` to function properly in certain circumstances.
> [PingOverride] Restore enums.py

- termino/termino.py
There was a flaw in the `restart` and `shutdown` command that didn't have an owner check. I have tested it with a friend and it no longer allows anyone who isn't an owner to run either command now.
> [Termino] Add owner check to restart and shutdown

- .github/workflows/run_precommit.yaml
- .pre-commit-config.yaml
Checks won't work until isort is at 5.12.0, which [does not support <3.10](https://github.com/home-assistant/core/issues/86892#issuecomment-1407763613).
> Bump isort to 5.12.0

- quotes/quotes.py
Good evening,
For the past 2 days, the web certificate for the API used in Quotes has expired, causing linked web requests to fail. This modification uses the `http` protocol instead of `https` to fix the problem temporarily while waiting for the problem to be fixed on the API side.
Thanks in advance,
Have a nice evening,
AAA3A
> [Quotes] Fix use of the API (with an expired certificate).

- tonguetwisters/tonguetwisters.py
Wasn't sure if the owner check was just something left in by mistake or what - also added a few more quotes so it looks like I did something either way!
> [Tonguetwisters] Remove owner only check(?) 

- gallery/gallery.py
Hi Kreu,
Noticed this bug today so decided to pr the changes:
- Bug fix - where the cog was **listening** to bots messages causing it to fall in a potential **loop** of 'deleting-sending-deleting'.
- (For example: In case of a **sticky msg** in the 'set gallery' channel the cog would keep on deleting the sticked message while the sticky cog would keep on sending a new message)
- **Bots are Ignored now**.
- The `galleryset add` and `galleryset remove` commands now accept **multiple channel** as arguments.
- Removed colons from `:` settings embed making it more user-readable.
- Added a few aliases: `showsettings`, `show`, `setting` (Hope its okay ) 
- Bumped the version
> [Gallery] Bug fix, Feature Update
