collectables/collectables.py

Just one more last little update from me before it goes live.
I cleaned up some of the comments and made most of the command be grouped.
Enjoy :D

Clean up of the repo and I made the commands be grouped

---

mcoc/mcoc.py

Command not group

---

ram/ram.py

Was just having a look through your code and noticed that there was a variable that wasn't being used. Just thought I'd point that out 👍

Remove unused variable

---

README.rst

Seeing as you're an approved cog creator now, I added the #support_othercogs channel as a way to get support.
😃👍🏼

[README] Add #support_othercogs as a way to get support

---

CHANGELOG.rst
advanceduptime/CHANGELOG.rst
dehoister/CHANGELOG.rst
docs/_au-cl.rst
docs/_dh-cl.rst
docs/_v-cl.rst
vinfo/CHANGELOG.rst

Update changelogs since `06/03/2021`.

[Docs] Update Cls

---

roleboards/roleboards.py

Added staticmethods to replace lambdas and basic touch ups.
Basically, just D.R.Y (Don't Repeat Yourself) updates (:

[RoleBoards] Basic touch ups

---

roleboards/roleboards.py
termino/termino.py

The old way actually didn't readd shutdown or restart :)

[Termino] Add shutdown and restart if they exist

---

docs/changelog_spoilerchannel.rst
docs/cog_spoilerchannel.rst
spoilerchannel/CHANGELOG.rst
spoilerchannel/README.rst
spoilerchannel/__init__.py
spoilerchannel/info.json
spoilerchannel/spoilerchannel.py

[Meta] Add SpoilerChannel cog

---

CHANGELOG.rst
docs/repo_changelog.rst

[Docs] Update changelogs for April

---

dehoister/dehoister.py

Adds an ignore list to have the dehoister ignore certain users. Doc strings might not be the best but it's me (:
If anything needs to be changed then lmk :D
Closes #61

[Dehoister] Add user blacklisting to various dehoister events and commands

---

vinfo/__init__.py
vinfo/vinfo.py

The rewrite Vinfo's been waiting for - multiple improvements to UI and now provides more information.

Vinfo rewrite

---

vinfo/vinfo.py

Add some more info about the managed ll node

---

.github/labeler.yml
README.rst
cogpaths/README.rst
cogpaths/__init__.py
cogpaths/cogpaths.py
cogpaths/info.json
docs/cog_cogpaths.rst
docs/index.rst
docs/repo_available_cogs_list.rst

[CogPaths] Initial Cog Revision

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/labeler.yml
.github/workflows/issue_labeler.yml
.vscodeignore

Fix an issue with the labeler, with some additional fields in the bug issue template, and adding `__pycache__` to `.vscodeignore`.

[Meta] Relevant fixes to the repository

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/docs.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/labeler.yml

Fix the labelers from creating new labels instead of adding existing ones.

[Workflows] Fix outdated labeler workflow

---

blackformatter/info.json

Changes the docs link to the actual page

[BlackFormatter] Fix docs link

---

raffle/helpers.py
raffle/parser.py

[Raffle] Fix AttributeErrors and TypeErrors through SafeMember object

---

raffle/commands/informational.py
raffle/commands/management/events.py
raffle/helpers.py
raffle/info.json

Limit each page to only 10 members, instead of using pagination page limits

[Raffle] v1.5.2 Reformat pagination in raffle members command

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/labeler.yml
README.rst
docs/cog_flags.rst
docs/index.rst
docs/repo_available_cogs_list.rst
flags/README.rst
flags/__init__.py
flags/flags.py
flags/info.json

[Flags] Initial revision of the cog

---

flags/converters.py
flags/flags.py
flags/functions.py

[Flags] Use converter for arguments

---

.github/FUNDING.yml

Seeing as the link doesn't work... *delet time*

[Meta] Remove Patreon

---

docs/cog_roleboards.rst
roleboards/README.rst
roleboards/info.json
roleboards/roleboards.py

[RoleBoards] v3.0.0 Cog Rewrite using Menus

---

consoleclearer/consoleclearer.py

[ConsoleClearer] Add owner-only checks

---

cogs.csv

[Cogs.CSV] Grammar fixes :D

---

raffle/commands/builder.py

Fix deletion of instruction message

[Raffle] Fix deletion of instruction message

---

raffle/commands/informational.py
raffle/utils/version_handler.py

[Raffle] Remove `not` from version validation

---

advanceduptime/uptime.py

Show system uptime as an optional setting

[AdvancedUptime] v3.2.0 Add system uptime information as an optional setting

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/labeler.yml
CODEOWNERS
cogs.csv
make.bat
ocs/info.json
pypi/__init__.py
pypi/info.json
pypi/pypi.py

Initial revision of the PyPi cog by Kreusada and OofChair

Initial revision of the PyPi cog

---

pypi/pypi.py

`commands.has_permissions` to `commands.bot_has_permissions`

[pypi] fix correct permission

---

pypi/pypi.py

[PyPi] Fix referencing errors

---

raffle/commands/builder.py

[Raffle] Fix complex raffles from continuing with unbound variables after timeout

---

captcha/api.py

[Captcha] Fix typo in captcha message

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/labeler.yml
cogs.csv
qr/__init__.py
qr/info.json
qr/qr.py

Initial revision of the QR cog.

[QR] Initial revision of the Cog

---

advanceduptime/uptime.py

Added check for bot owner in uptimeset

[AdvancedUptime] v3.3.0 Add owner check to uptimeset

---

captcha/base.py
pingoverride/ping.py

Fixes the invalid logging date for captcha.
Closes #184

[Captcha] Fix invalid log date

---

captcha/commands/settings.py

This removes and replaces the vague responses in the captcha cog. This PR is discussed [here](https://discord.com/channels/744572173137477692/769165401879478302/922680562530025544)

[Captcha] Removal of vague responses

---

.github/labeler.yml
cogs.csv
docs/cog_replynoping.rst
docs/index.rst
pyproject.toml
replynoping/README.rst
replynoping/__init__.py
replynoping/info.json

[ReplyNoPing] Initial revision of the cog

---

raffle/info.json
raffle/utils/helpers.py

Calls the lambda function `now`

[Raffle] Call `now`

---

advanceduptime/uptime.py

fix for `OverflowError: cannot convert float infinity to integer` error.

[advanceduptime] OverflowError: cannot convert float infinity to integer error.

---

termino/termino.py

if there's not a confirmation message
Returns `True` in the confirmation check function if there isn't a confirmation message (if someone doesn't have one setup they can't run restart or shutdown)

[Termino] Allow restart/shutdown to be ran

---

cogs.csv
docs/cog_embedcreator.rst
docs/index.rst
embedcreator/README.rst
embedcreator/__init__.py
embedcreator/embedcreator.py
embedcreator/info.json
pyproject.toml

Adds the new EmbedCreator cog which allows you to create rich embeds using buttons and modals. There is a lot of bug testing that needs to be done before this can be merged.

Add EmbedCreator cog

---

gallery/gallery.py

Hi kreu,
Was messing around with it and added the features so thought of pr-ing the changes to the main cog.
- Ability to add multiple roles as whitelisted.
- Ability to remove a single whitelisted role instead of removing all to remove one
- Running the `<p>galleryset role <role>` twice with same role removes the role
- Support for webp image type, and tenor, giphy gifs
- Rename the settings title to `Gallery Settings`

[Gallery] Feature update
